import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "IRCTC Pay",
  description: "Generated by Ipsator",
  robots: "noindex, nofollow",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
